apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-svc-v1
 # annotations:
 #   "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: details-svc
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details-svc
      version: v1
  template:
    metadata:
      labels:
        app: details-svc
        version: v1
    spec:
      serviceAccountName: ctibco-details-svc
      containers:
      - env:
        - name: DETAILS_MY_PORT
          value: "9082"
        image: details
        name: details
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            port: 7777
            path: /_ping
          initialDelaySeconds: 15
          periodSeconds: 5
        resources:
          requests:
            memory: 500Mi
            cpu: 500m
          limits:
            memory: 900Mi
            cpu: 1000m
        ports:
        - containerPort: 9082
      imagePullSecrets:
        - name: regcred
