apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service_account.yaml
- service.yaml
commonLabels:
  env: dev
images:
- name: 172.31.28.242:8083/details
  newName: 172.31.28.242:8083/details
  newTag: 2.2.2
