apiVersion: v1
kind: Service
metadata:
  name: details-svc
  labels:
    app: details-svc
    service: details-svc
spec:
  ports:
  - name: http
    protocol: TCP
    nodePort: 33133
  selector:
    app: details-svc
  type: NodePort
